name: example
description: Example using Flutter Duration Picker
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  duration_picker:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true